### ISSUE TITLE
console is printing 422 errors before the catch

### ISSUE THREAD

**Issue by garetmckinley** [heroku/react-refetch#165] opened 2017-02-16 17:23 UTC
## Reproduction

http://www.webpackbin.com/NJ1BUaCuG

```jsx
import React from 'react';
import {render} from 'react-dom';
import { connect, PromiseState } from 'react-refetch'

const AppComponent = () => (
  <div>
    Hello World
  </div>  
);

const App = connect(props => ({
  userFetch: {
    url: 'http://httpstat.us/422',
    catch: (err) => console.warn("there was an error", err)
  }
}))(AppComponent)

render(<App />, document.querySelector('#app'));
```

## Issue

Even though the `userFetch` endpoint has a `catch`, the browser still prints a `422` error before the `catch` executes.

![screen shot 2017-02-16 at 12 21 04 pm](https://cloud.githubusercontent.com/assets/1624279/23032553/ae7f8942-f442-11e6-9471-56c950b06d57.png)

## Expectation

The `catch` should intercept all errors and status codes and allow you to handle/silence them.

**Comment by ryanbrainard** [comment] 2017-02-17 01:16
I'm pretty sure this is expected behavior internal to any failed network callouts in Chrome, and I'm not sure of a way to override it. For example, just try running this directly with `fetch`:

    fetch('http://httpstat.us/422')

and you'll get:

![image](https://cloud.githubusercontent.com/assets/966764/23045059/5a88a1d0-f4e6-11e6-8dcc-bb01fe1c02d4.png)

Compare that to running it in Node:

```node
> fetch('http://httpstat.us/422')
Promise { <pending> }
```

This all happens before the `catch` is run and is a side effect (i.e. it does not impact the resulting `PromiseState`). 

Also, just a side note: Not sure if you were using a simplified `catch` just an example for this issue, but (at least in the real world) you should be supplying an alternative URL to fetch from like this:

```jsx
userFetch: {
    url: 'http://httpstat.us/422',
    catch: (err) => {
      console.warn('there was an error', err)
      return 'http://httpstat.us/200'
    },
  }
```

Note, this `catch` in the URL mappings is different from the semantics of `Promise.catch` and also different from `PromiseState.catch`.

I'm going to close this since I don't think this is an issue with this library, but rather with the browser. Please feel free to re-open if needed.

**Closed by ryanbrainard** 2017-02-17 01:16 UTC

**Comment by garetmckinley** [comment] 2017-02-17 02:21
@ryanbrainard So if an API endpoint is returning any error code, there's no way to silence it?

**Comment by ryanbrainard** [comment] 2017-02-17 02:35
Correct, but that's really a question for Chrome, not this library. React Refetch is not writing to the console in this case.

**Comment by ryanbrainard** [comment] 2017-02-17 02:37
Related: http://stackoverflow.com/questions/14337351/can-i-prevent-the-chrome-developer-tools-console-from-logging-image-404-errors
