### ISSUE TITLE
Question About Refetching

### ISSUE THREAD

**Issue by jwdotjs** [heroku/react-refetch#26] opened 2015-12-28 00:49 UTC
```js
export default connect((props) => {
  const url = '/api/devices';
  return {
    devicesSearch : url,
    refreshDevices : () => ({
      devicesSearch : {
        url,
        refreshing : true,
      },
    }),
  };
})(DevicesList);
```

I have a question about line 148 on connect.js (https://github.com/heroku/react-refetch/blob/master/src/components/connect.js#L148)

Currently, it checks if the mapping is equal between the previous request and the next one. From my local testing, this causes a mapping to be refetched only once, then that mapping will be equal to the previous mapping on subsequent requests.

In my example above, in the DevicesList component I have a button that allows the user to click and refresh the list to view the latest devices. They can click the button as many times as they want, but it will only make one request currently, then the equality check returns true between previous and next mapping so the subsequent refetches will fail and that seemed counter-intuitive (unless I'm doing something incorrectly). 

Should I be adding additional keys to my mapping so that the comparison check returns false? Should I be passing in a comparison check based on something specific?

If not, it seems to me that it would make more sense here to see if the the mapping is still valid and always refetch regardless of equality, but I'm not sure what that would affect.

I created a local branch to set the `refreshing` flag to false after a request is complete if `refreshing` was true and in the default equality check I added `refreshing` to the array of keys to test against for equality, and that works, but it doesn't seem like a good solution since `refreshing` is an optional key for a refresh mapping. If a user didn't pass that key in they would still encounter the same issue so I wanted to get everyone's thoughts on other solutions.

**Comment by ryanbrainard** [comment] 2015-12-29 02:42
If you want to always refetch regardless of the request changing or not, you can set `force: true` in the request. This is generally not advisable for top-level requests, but makes sense for requests inside of functions. Alternatively, you can set `comparison` to some value to check equality with a custom value. 

With your current setup, are you finding that one fetch happens on component mount, then one refetch happens on the first user click, and then no more refetches for subsequent clicks; or, are finding that only the first fetch happens on component mount? From your description, it sounded like former, but I would expect the latter because the request didn't change even on the first refetch. I'm going to leave this issue open for your response and so I can do some testing of the behavior here once I'm back at a computer.

**Comment by jwdotjs** [comment] 2015-12-29 14:20
When the component mounts, I see one fetch. Then when the user clicks a button I see one refetch.

The request changes and the library allows for one refetch because the mapping changes from not having the refetch key set (on the original fetch) to having the refetch key set when the user first clicks the button (through the function refresh function passed into the component).

**Comment by ryanbrainard** [comment] 2015-12-29 19:43
> When the component mounts, I see one fetch. Then when the user clicks a button I see one refetch.

Hmm, I'll need to investigate that. I would only expect the initial fetch. 

> The library currently allows for one fetch and one refetch because the mapping changes from not having the `refreshing` key set (on the original fetch) to having the `refreshing` key set to true when the user first clicks the button (through the function refresh function passed into the component). 

It shouldn't be comparing that, but I'll need to take a closer look. 

> I know, setting force to true will allow it to continue refetching for each button click, but I'm wondering if it would make more sense to just see if `refreshing` is set and true and always allow a refetch if the mapping is valid. 

There are use cases to set refreshing on component mount and cases when a refetch should not occur even on a user action, so I don't want to conflate force and refreshing and chose to keep them separate, explicit attributes. 

> It seems to me like each individual component should be responsible for determining when a user clicks on a button if a refetch should actually trigger or not through the components all validation checks, not through the react-refetch library by passing in `force: true`. 

See above, and also remember that you can pass arguments to fetch functions, so you could even pass in `force` at runtime to incorporate it into your validation routine.

**Comment by jwdotjs** [comment] 2015-12-29 19:51
> It shouldn't be comparing that, but I'll need to take a closer look.

I believe it is using the same mapping because the key is the same for both the initial fetch and refetch: `devicesSearch` (in the example above) 

> There are use cases to set refreshing on component mount and cases when a refetch should not occur even on a user action, so I don't want to conflate force and refreshing and chose to keep them separate, explicit attributes.

Ok, later tonight I will create a pull request to update the readme's Manual Refetching section to describe the mapping, comparison, and force attribute so other users don't run into the same situation, if that works for you. 

Thanks for your help :)

**Comment by ryanbrainard** [comment] 2016-01-03 07:15
> I believe it is using the same mapping because the key is the same for both the initial fetch and refetch: `devicesSearch` (in the example above)

Sorry for the delay. I finally got some time to try this out, but I cannot reproduce the issue you were seeing with the first refetch. I copied your code snipped above into a sample app of mine, but I only see the initial fetch happening on page load. The fact that they are both using the same key is exactly why there should not be a refetch. When I tried calling it `devicesSearch2` inside the function, it as you mentioned. Are you sure you didn't have a typo in the key name? I way you described the behavior in #28 is correct, so I'm going to pull that in and close this issue, but please let me know if you're still having problems with this.

**Closed by ryanbrainard** 2016-01-03 07:15 UTC
Labels: question

**Comment by ryanbrainard** [comment] 2016-01-03 07:36
Err, scratch half of what I just said. I re-read what you have in the readme:

> In the above example, if props.userId is 1, `/users/1` would be fetched, then refetched once if triggered, but not refetched a second time if re-triggered.

This is not the behavior that is expected or what I experienced when I tried this. With `force: true` and no change to the props, it should never refetch. I'm going to update the example to include `force: true`, but still curious about the behavior you saw. If you're still seeing that, please re-open this. 

@hnordt mentioned he also ran into the general `force: true` issue. @hnordt, did you see this same behavior of a first (but not second) refetch that @jwdotjs saw?

**Comment by jwdotjs** [comment] 2016-01-03 15:46
Here is a more complete example with the full component:

```jsx
import React from 'react';
import moment from 'moment';
import { map } from 'lodash';
import { connect, PromiseState } from 'react-refetch';

class DeviceMessages extends React.Component {
  static propTypes = {
    history : React.PropTypes.object.isRequired,
    params : React.PropTypes.shape({
      userId : React.PropTypes.string.isRequired,
    }).isRequired,
    refreshMessages : React.PropTypes.func.isRequired,
    deviceMessageSearch : React.PropTypes.instanceOf(PromiseState).isRequired,
  }

  state = {
    messages : [],
  }

  renderDeviceMessages() {
    const { deviceMessageSearch } = this.props;
    const allSearches = PromiseState.all([ deviceMessageSearch ]);

    if (allSearches.pending) {
      return 'Loading Device Messages...';
    } else if (allSearches.rejected) {
      return 'There was an error loading messages';
    }

    const [ messages ] = allSearches.value;
    if (! messages.length) {
      return <h3>No new messages.</h3>;
    }

    const rows = map(messages, (message, key) => {
      const { device, place } = message;
      return (
        <tr key={key}>
          <td>{device && device.name || '-'}</td>
          <td>{place.name}</td>
          <td>{message.message}</td>
          <td>{message.updated_at ? moment(message.updated_at).fromNow() : '-'}</td>
        </tr>
      );
    });

    return (
      <table className='collapsable-table'>
        <thead>
          <tr>
            <th>Device Name</th>
            <th>Room Name</th>
            <th>Message</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {rows}
        </tbody>
      </table>
    );
  }

  render() {
    return (
      <div>
        <h2>Device Messages</h2>
        <button onClick={this.props.refreshMessages}>Refresh messages</button>
        {this.renderDeviceMessages()}
      </div>
    );
  }
};

export default connect((props) => {
  const deviceMessageUrl = `${process.env.API_URL}api/users/${props.params.userId}/device-messages`;
  return {
    deviceMessageSearch : deviceMessageUrl,
    refreshMessages : () => ({
      deviceMessageSearch : {
        url : deviceMessageUrl,
        method : 'GET',
        refreshing : true,
        // force : true,
      },
    }),
  };
})(DeviceMessages);
```

Sample response object from DB:
```
created_at: "2015-12-27T20:54:28.018Z"
device: { id : 5, name : "hoosier_turtle" },
id: 247
message: "Motion Detected"
place: { id : 1, name : "Kitchen" },
updated_at: "2015-12-27T20:54:28.018Z"
```

Request 1 On Component Mount:
![screen shot 2016-01-03 at 8 42 17 am](https://cloud.githubusercontent.com/assets/246603/12079430/ebb168f2-b1f5-11e5-8b92-459f5494a3ae.png)

Request 2 On Button Clicked:
![screen shot 2016-01-03 at 8 42 58 am](https://cloud.githubusercontent.com/assets/246603/12079437/08d24b90-b1f6-11e5-82dc-3db074a9c97c.png)

When I click a button for the second time, nothing happens.

------

Switching to `force: true` allows me to click and refresh data as much as I want:

![screen shot 2016-01-03 at 8 44 17 am](https://cloud.githubusercontent.com/assets/246603/12079442/4c6fb220-b1f6-11e5-9b79-0f611cbfcfd8.png)

**Comment by ryanbrainard** [comment] 2016-01-03 17:47
@jwdotjs Ah, I see what the problem is! It is not the `refreshing: true` (which is not considered for equality), but that you are specifying `method: 'GET'` only on the request in the function. `GET` is the default method, but the defaults are not applied until after the equality check. This is mostly a bug in Refetch, but I need to re-think if there was any reason it was done in this order. For now, if you just remove the `method: 'GET'`, it should work for you. I'll file a bug for this as well.

**Comment by jwdotjs** [comment] 2016-01-03 17:52
Gotcha! Sorry for missing that piece in the first example.
